---
title: Cookbook
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Running the analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Overview

This cookbook provides a step-by-step guide to running the PACTA for Supervisors analysis using the `pacta.multi.loanbook` package. The analysis is designed to help financial supervisors assess the alignment of banks' loan books with the Paris Agreement goals.

## What is the PACTA for Supervisors analysis?

PACTA for Supervisors is based on the PACTA methodology, which assesses the alignment of financial portfolios with climate goals utilizing forward-looking asset-based company data (ABCD) that is linked to financial assets and compares the production profiles of those companies with technology and emissions pathways from climate transition scenarios at the sector and/or technology level.

## Who is this tool built for?

The PACTA for Supervisors analysis is primarily designed to be run by financial supervisors on their own, with minimal additional guidance. However, it can also be a useful tool for any other user, in case they would like to run a PACTA analysis on multiple loan books.

The main difference between this tool and the individual PACTA for Banks software packages is that this tool aims to facilitate the analysis of multiple loan books at once, streamlining the process as much as possible, to keep the burden for the user to a minimum. As such it is a helpful tool for anyone who would like to run a PACTA analysis on multiple loan books.

## What can the results of the PACTA for Supervisors analysis be used for?

Financial supervisors or regulators can use the results of the analysis to assess the alignment of banks' loan books with the Paris Agreement goals, to identify sectors where banks may need to take action to improve alignment, and to screen the financial system for potential climate-related transition risks. The analysis can be parameterised in different ways to explore patterns across the analysed loan books. If run by private institutions, the results may additionally be used to identify opportunities for climate-aligned investments, as well as for detecting individual counterparties that may be exposed to climate-related transition risks and may therefore require dedicated focus in the risk management process.

Users will be able to obtain both tabular outputs and plots that can be used for any of the above use cases. The tabular output further enables processing of the alignment results in other models or tools, for example as an input into financial risk models, or as a recurring input into internal monitoring systems.

The level of granularity of the outputs allows for a systematic analysis of climate alignment starting at the financial system level (across all analyzed loan books together), down to the individual counterparty level, and across sectors and technologies. Grouping of the results at any of these levels by additional dimensions can easily be achieved using the configuration file.

## What are the main steps of the analysis?

The main steps of the analysis are as follows:

1. Data preparation: Prepare the ABCD data and optionally a custom sector split.
2. Matching process: Match the raw loan books to the ABCD data.
3. Prioritization of loan books; Match success and coverage diagnostics: Prioritize the matched loan books and analyze their coverage.
4. Run PACTA for Supervisors analysis: Run the analysis based on the parameters set in the `config.yml` file.

This cookbook will guide you through each of the steps of the analysis in detail, explain the required input data sets and software, and provide guidance on how to interpret the results.

# Preparatory Steps

This section provides an overview of the preparatory steps that need to be taken before running the PACTA for Supervisors analysis. It includes information on the required input data sets, the required software, and the how to setup the project folder and file structure. Finally, it provides a checklist of the steps that need to be taken before running the analysis, summarizing in brief the steps explained in more detail before.

## Required Input Data Sets

The PACTA for Supervisors analysis requires a number of input data sets to run. Some of these can be obtained from external sources, while others need to be prepared by the user. Furthermore, some of the input data sets are optional and there inclusion will depend on the settings provided in the `config.yml` file. 

The main input data sets required for the analysis are:

### Asset-based Company Data (ABCD)

This data set provides information on the production profiles and emission intensities of companies active in the following real economy sectors: Automotive (light-duty vehicles) manufacturing, aviation, cement production, coal mining, upstream oil & gas extraction, power generation, and steel production. The ABCD is typically obtained from third party data providers. However, it is possible to prepare the ABCD yourself or complement an external data set with entries that may not be covered out of the box.

The ABCD data set must be an XLSX file and contains the following columns:
ADD

Further information on how to obtain ABCD for PACTA and documentation of the individual sectors and data points can be found here LINK.

### Scenario Data

The scenario data set provides information on the trajectories of technologies/fuel types and of emission intensities pathways for each of (or a subset of) the sectors covered in PACTA.

For sectors with technology level trajectories, the data set provides the TMSR and SMSP pathways based on the Market Share Approach, an allocation rule that implies all companies active in a sector have to adjust their production in a way that keeps market shares constant and solves for the aggregate climate transition scenario (LINK to the market share documentation).

The target market share scenario data set must be a CSV file and contains the following columns:
ADD

For sectors that do not have technology level pathways, PACTA uses the Sectoral Decarbonization Approach (SDA), an allocation rule that implies that all companies in a sector have to converge their physical emission intensity at a future scenario value - e.g. in the year 2050. This implies that more polluting companies have to reduce their physical emissions intensity more drastically than companies using cleaner technology. It does not have any direct implications on the amount of units produced by any company (LINK to the SDA documentation).

The SDA scenario data set must be a CSV file and contains the following columns:
ADD

While the raw input values of the scenarios are based on external third party organisations - such as the International Energy Agency (IEA), the Joint Research Center of the European Commission (JRC), or the Institute for Sustainable Futures (ISF) - the input data set for PACTA must be prepared using additional steps, which are documented publicly on the following GitHub repositories:

- [pacta.scenario.data.preparation](https://github.com/RMI-PACTA/pacta.scenario.data.preparation)
- [workflow.scenario.preparation](https://github.com/RMI-PACTA/workflow.scenario.preparation)

Since RMI has taken over stewardship of PACTA the prepared scenario files can also be accessed as CSV downloads the [PACTA website](https://pacta.rmi.org/pacta-for-banks-2020/) under the "Methodology and Documents" tab of the "PACTA for Banks" section. The files are usually updated annually based on the latest scenario publications.

### Raw Loan Books

ADD

## Required Software

## Project Setup

## Checklist of Preparatory Steps

### Config

All of the functions needed to run a PACTA for Supervisors analysis take a `config` argument, which can either be a path to a `config.yml` file (see `vignette("config_yml")`) or a config list object containing previously imported settings from a `config.yml` file. All of the settings/options are configured with this `config.yml` file.

### Input/Output folder structure

# Running the Analysis

## Simple Overview of the Workflow

### Setup

You'll likely want to load the package and save the path to the `config.yml` file in a variable first:

```r
library(pacta.multi.loanbook)
config_path <- "config.yml"
```

### Data preparation

The first step of the analysis is to prepare your input data sets for the requirements of the analysis. Your ABCD data will need to be prepared and you can optionally use a custom sector split, that will also need to be prepared. The relevant function is `prepare_abcd()`, which takes configurations from the `config.yml` that you have prepared. The function will store intermediary files in a sub-directory in your `output` folder. You can run this function as follows:

```r
pacta.multi.loanbook::prepare_abcd(config_path)
```

### Matching process

To run the matching process, you will use the `match_loanbooks()` function. This will read the raw loan books from yout inputs and attempt to match them to the prepared ABCD data from the previous step. The function will store matched loan book files in a sub-directory in your `output` folder. You can run this function as follows:

```r
pacta.multi.loanbook::match_loanbooks(config_path)
```

After the matching process is complete, you will need to do some manual matching.

### Prioritization of loan books; Match success and coverage diagnostics

The next step is to prioritize the manually verified matched loan books and analyze their coverage, both relative to the raw loan book inputs and to the production capacity in the wider economy. Prioritizing the loan books means that you will only keep the best identified match for each loan and use that in the following steps of the analysis. You will probably want to check the status of your loan book and production coverage several times, as it is rare to get to the desired level of matching in one iteration. This means you may want to repeat the previous step and this step a number of times to reach the best possible outcome. To prioritize your matched loan books and calculate display the coverage diagnostics, you will use the `prioritise_and_diagnose()` function. This call will store matched prioritized loan book files and coverage diagnostics in a sub-directory in your `output` folder.

```r
pacta.multi.loanbook::prioritise_and_diagnose(config_path)
```

### Run PACTA for Supervisors analysis

The final step is running the analysis based on the parameters you have set in the `config.yml` file. This entails both a standard PACTA for Banks analysis and the calculation of the net aggregate alignment metric. For both parts of the analysis, outputs will be stored in a sub-directory in your `output` folder and comprise tabular outputs and plots.
To run the analysis on all of your previously matched and prioritized loan books, you will use the `analyse()` function.

```r
pacta.multi.loanbook::analyse(config_path)
```

## Details - Data Preparation

## Details - Matching Process

## Details - Prioritization of loan books; Match success and coverage diagnostics

## Details - Run PACTA for Supervisors analysis

# Interpretation of Results

## Data Dictionary

## Interpreting the Coverage Diagnostics

## Interpreting the PACTA Outputs and Graphs

## Interpreting the Net Aggregate Alignment Metric Outputs and Graphs
