#' Data dictionary
#'
#' An overview of the output data sets generated by the package, their data types,
#' and the definitions of the variables.
#'
#' @format ## `data_dictionary`
#' \describe{
#'   \item{dataset}{Name of the dataset}
#'   \item{column}{Name of the column}
#'   \item{typeof}{Data type of the column}
#'   \item{definition}{Description of what the column stands for}
#'   \item{value}{Which values are allowed for the column}
#'   ...
#' }
#'
#' @details
#' For more details see the help vignette:
#' \code{vignette("data_dictionary", package = "workflow.multi.loanbook")}
#'
#' @source internal
"data_dictionary"

#' ABCD test data
"abcd_test_data"

#' Loan book test data
"loanbook_test_data"
